name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Print SSH_PRIVATE_KEY
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Deploy to VPS
        run: scp -r . root@217.196.49.92:/root/project/royalMercaderistasFrontend
